### ISSUE TITLE
Add light mode and light/dark mode button

### ISSUE THREAD

**Issue by durmusrasit** [senchabot-opensource/monorepo#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by batuhanbaybas** [comment]
is light mode classes are available ?

**Comment by mertsabinov** [comment]
Hello,

Before completing this issue, it is necessary to determine the colors to be used for the light theme. Currently, these colors are not specified in the `theme.js` file. The required steps to be taken are as follows:

1. Determine the colors to be used for the light theme.
2. Add these colors to the relevant sections in the `theme.js` file.

Please consider this matter when completing the issue.

Thank you!
