### ISSUE TITLE
User manual needs to be written for connecting Twitch and Discord

### ISSUE THREAD

**Issue by sevilayerkan** [senchabot-opensource/monorepo#202]
**Is your feature request related to a problem? Please describe.**
- A new user manual needs to be written for new users for connect Senchabot to Twitch and Discord.
- It would be much better to include screenshots and to use plain language.

**Describe the solution you'd like**
- For textbase documentation example you can checkout : 
#198

**Comment by durmusrasit** [comment]
> is this written in go or ts?

Discord bot is written in TypeScript and Twitch bot is written in Go.

**Comment by 6fy** [comment]
I support this idea

**Comment by igdiaysu** [comment]
Cancel.
