### ISSUE TITLE
When a "*x" is added to the end of the command, spam the message.

### ISSUE THREAD

**Issue by igdiaysu** [senchabot-opensource/monorepo#209]
Example Dialog

> User : `!go`
> 
> Senchabot: `Let's goo`
> 
> User: `!go*3`
> 
> Senchabot: `Let's goo`
> Senchabot: `Let's goo`
> Senchabot: `Let's goo`

**Comment by usirin** [comment]
IMO, this needs a fully thought out "syntax parsing system". It can get pretty dirty pretty early if we don't think about how this can scale in the future first.

**Comment by durmusrasit** [comment]
I am closing this issue as it will cause problems in the parsing system and clog the bot system with spam.
