### ISSUE TITLE
Add Senchabot logo to auth page

### ISSUE THREAD

**Issue by durmusrasit** [senchabot-opensource/monorepo#344]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a Senchabot logo on the auth page and when clicking that logo it redirects to the https://senchabot.app

**Describe the solution you'd like**
The same logo can be taken and put in the AppBar. I think the `<AppBarTitle />` component might be suitable this job. Also, we can turn the `<AppBarTitle />` component in to a general component like `<Logo />` and turn it into our logo component that we can use anywhere.

**Comment by Vayras** [comment]
@durmusrasit I would like to work on this issue , can you please assign me to this , also can you please tell me more about the issue

**Comment by muhammed-gumus** [comment]
I can
