### ISSUE TITLE
Feature/Bug: In Twitch bot "/" based command support 

### ISSUE THREAD

**Issue by sevilayerkan** [senchabot-opensource/monorepo#93]
**Is your feature request related to a problem? Please describe.**
Sencha should be support to `/` based Twitch commands like `/announce` and `/clear`. 

Here is a example usecase: `!acmd commandname /announce message`

Now when we tried this we aren't getting any response from Sencha as shown in ss:
![image](https://user-images.githubusercontent.com/22706692/235802720-8b44a0fd-05b2-4bff-8b4d-64d531f704a5.png)

**Comment by sevilayerkan** [comment]
This issue is also connected with #87

**Comment by sevilayerkan** [comment]
If you want we can do this issue later due to mvp planning.

**Comment by durmusrasit** [comment]
Thanks!
Such commands and functions will be able to be assigned to commands with a system that will be developed after MVP. So I'm closing this issue for now.
